name: typos on PR
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling on Markdown files
        uses: crate-ci/typos@master
        with:
          files: ./*.md
